image: "nikolaik/python-nodejs:python3.8-nodejs14-alpine"


stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
    - node_modules

build:
  stage: build
  script:
    - echo "Building"
    - npm install
    - npm install @angular/cli
    - pip install virtualenv
    - ./create-venv
    - source venv/bin/activate
    - pip install wheel
    - ./deploy front test
    - ./deploy build front prod
  artifacts:
    paths:
      - server/templates
      - server/static

test-frontend:
  image: "node:14-alpine3.12"
  stage: test
  script:
    - echo "Testing frontend"
    - npm run test


test-backend:
  image: "python:3.8-alpine"
  stage: test
  script:
    - echo "Testing backend"
    - source venv/bin/activate
    - python -m pytest

frontend-lint:
  image: "node:14-alpine3.12"
  stage: test
  script:
    - echo "Lint frontend"
    - npm run lint:ts

backend-lint:
  image: "python:3.8-alpine"
  stage: test
  script:
    - echo "Lint backend"
    - source venv/bin/activate
    - python -m pylint -d duplicate-code server
    - python -m pylint -d duplicate-code flask-api
