image: "nikolaik/python-nodejs:python3.8-nodejs14-alpine"

# before_script:
#   - rm ~/gitlab-runner/.bash_logout

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building"
    - python -V
    - npm install
    - npm install @angular/cli
    - ./deploy build front prod
    - mkdir build
    - touch build/info.txt
    - docker login registry.example.com
    - docker build -t registry.gitlab.com/sepsseven/miniburn .
    - docker push registry.gitlab.com/sepsseven/miniburn
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Testing"
    - ./deploy front test
    - npm run test
    - pytest
    - test -f "build/info.txt"