image: "nikolaik/python-nodejs:python3.8-nodejs14-alpine"

# before_script:
#   - rm ~/gitlab-runner/.bash_logout

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building"
    - python -V
    - npm install
    - npm install @angular/cli
    - ./deploy build front prod
    - mkdir build
    - touch build/info.txt
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules
      - server/templates
      - server/static
    
  artifacts:
    paths:
      - build/

test-frontend:
  stage: test
  script:
    - echo "Testing frontend"
    - ./deploy front test
    - npm run test
    - test -f "build/info.txt"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules

test-backend:
  stage: test
  script:
    - echo "Testing backend"
    - ./deploy front test
    - pytest
    - test -f "build/info.txt"

static-analysis:
  stage: test
  script:
    - echo "Testing backend"
    - ./deploy front dev
    - ./deploy api dev
    - npm run lint:ts
    - pylint -d duplicate-code server
    - pylint -d duplicate-code flask-api
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules