image: "node:latest"

# before_script:
#   - rm ~/gitlab-runner/.bash_logout

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building"
    - ./deploy build front prod
    - ./deploy front test
    - npm install
    - mkdir build
    - touch build/info.txt
  artifacts:
    paths:
      - build/


test:
  stage: test
  script:
    - echo "Testing"
    - npm run test:all
    - test -f "build/info.txt"