image: "nikolaik/python-nodejs:python3.8-nodejs14-alpine"

# before_script:
#   - rm ~/gitlab-runner/.bash_logout

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building"
    - python -m venv venv
    - source venv/bin/activate
    - pip install wheel
    - ./deploy front test
    - npm install
    - npm install @angular/cli
    - ./deploy build front prod
    - mkdir build
    - touch build/info.txt
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules
      - server/templates
      - server/static
      - venv
    
  artifacts:
    paths:
      - build/

test-frontend:
  image: "node:latest"
  stage: test
  script:
    - echo "Testing frontend"
    - npm run test
    - test -f "build/info.txt"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules


test-backend:
  image: "python:3.8-alpine"
  stage: test
  script:
    - echo "Testing backend"
    - source venv/bin/activate
    - pytest
    - test -f "build/info.txt"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - venv
      - server/templates
      - server/static

static-analysis:
  stage: test
  script:
    - echo "Testing backend"
    - source venv/bin/activate
    - npm run lint:ts
    - pylint -d duplicate-code server
    - pylint -d duplicate-code flask-api
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules
      - venv