image: "nikolaik/python-nodejs:python3.8-nodejs14-alpine"


stages:
  - dependencies
  - build
  - test

cache-node-dependencies:
  image: "node:14-alpine3.12"
  stage: dependencies
  script:
    - echo "Installing node dependencies"
    - npm install
    - mkdir build
    - touch build/info.txt
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - node_modules

cache-angular-cli:
  image: "node:14-alpine3.12"
  stage: dependencies
  script:
    - echo "Installing ng dependencies"
    - npm install @angular/cli
    - mkdir build
    - touch build/info.txt
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - node_modules

cache-pypi-dependencies:
  image: "python:3.8-alpine"
  stage: dependencies
  script:
    - echo "Installing pypi dependencies"
    - python -m venv venv
    - source venv/bin/activate
    - pip install wheel
    - ./deploy front test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - venv

build:
  stage: build
  script:
    - echo "Building"
    - ls venv/bin
    - python -m venv venv
    - source venv/bin/activate
    - ./deploy build front prod
    - mkdir build
    - touch build/info.txt
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules
      - venv
  artifacts:
    paths:
      - server/templates
      - server/static

test-frontend:
  image: "node:14-alpine3.12"
  stage: test
  script:
    - echo "Testing frontend"
    - npm run test
    - test -f "build/info.txt"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules


test-backend:
  image: "python:3.8-alpine"
  stage: test
  script:
    - echo "Testing backend"
    - source venv/bin/activate
    - python -m pytest
    - test -f "build/info.txt"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - venv

frontend-lint:
  image: "node:14-alpine3.12"
  stage: test
  script:
    - echo "Lint frontend"
    - npm run lint:ts
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules

backend-lint:
  image: "python:3.8-alpine"
  stage: test
  script:
    - echo "Lint backend"
    - source venv/bin/activate
    - python -m pylint -d duplicate-code server
    - python -m pylint -d duplicate-code flask-api
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - venv
