version: '3'
services: 
    api:
        build: flask-api/
        ports: 
            - "8000:5000"
        environment: 
            MONGO_DB: miniburn
            MONGO_HOST: 127.0.0.1
            MONGO_PORT: 27017